Added camera and photo library image options.
ph1ps/Food101-CoreML pull request #1
Opened 2017-12-22 01:42 UTC by GraysonMartin

Users can upload images from photo library or camera.

2017-12-22 15:03 UTC, GraysonMartin commented
@ph1ps Oops. Sorry, didn't mean to do that. Thanks!

2017-12-23 13:06 UTC, ph1ps requested changes
Could you please add another commit to this PR with the permissions changed?

2017-12-23 15:02 UTC, GraysonMartin commented
I apologize. To be honest, I didn't even realize that I changed those permissions, and I have no idea on how to change them back. If you could provide some help on how to do this, I would be happy to change the permissions. Thank you.

2017-12-23 15:10 UTC, ph1ps approved these changes

2017-12-23 15:10 UTC, merged